org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft and Forge versions
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.1.76
forge_version_range=[47.1.1,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

# Mod information
mod_id=overloadgenerators
mod_name=Overload Generators
mod_license=MIT
mod_credits=Coding Help: Gemini
mod_version=2.0.0
mod_group_id=net.michanide.overloadgenerators
mod_authors=michanide
mod_description=A Mekanism addon that adds insane generators.\nThis is a joke mod. DO NOT TRY TO RUN THESE GENERATORS AT MAXIMUM RATE.

## Dependency Properties
mekanism_version=10.4.15.75
mekanism_version_range=[10.4.0,)